### ISSUE TITLE
"false" being spammed in Minecraft Log

### ISSUE THREAD

**Issue by Platalian** [Flemmli97/TenshiLib#1]
#### Issue (The better the description the better i can solve the issue):
"false" being spammed in the log after installing 1.1.1 , rolled back to 1.1.0 and no more spam, seems to be an issue with 1.1.1 only.

#### Steps to reproduce:
Install TenshiLib-1.12.2-1.1.1.jar and run.

#### Affected Versions (Latest is NOT a version):

- Minecraft: 1.12.2
- Forge: 14.23.5.2831
- TenshiLib: 1.1.1

#### Logs (Use a site like pastebin, gist etc. DONT COPY PASTE THE LOG IN HERE): 
https://paste.ee/p/Ik8cT

**Comment by Flemmli97** [comment]
already aware and fixed. just havent released it yet
