### ISSUE TITLE
Minecraft won't load

### ISSUE THREAD

**Issue by Nekkok** [Flemmli97/TenshiLib#2]
Issue: https://crashy.net/9ZNbLZ6gk4Dj85NpZhLF

Steps to reproduce:
As said, the game won't load with this and Improved Mobs 1.8 ((Fabric) installed. I could provide more info if required. Thanks in beforehand :)

- Minecraft 1.18.1
- Fabric 0.12.12 / FabricAPI 0.45.1
- TenshiLib 1.4.0 Fabric

**Comment by Flemmli97** [comment]
fixed 5433b0fdfa7b7dcbb78b61f118f0e98fe8d3cd00
