### ISSUE TITLE
[Feature Request]: Seems like you've opt out on third party usage of the mod on Curseforge

### ISSUE THREAD

**Issue by FederAndInk** [Flemmli97/TenshiLib#8]
### Suggestions

Because of your decision to opting out to "allow the distribution of this project outside the curseforge-overwolf ecosystem", now cf is starting enforcing that stuff, so your mod is effectively undownloadable from third party launchers (MultiMC, PolyMC, GDLauncher, ...), this is especially annoying on Linux as curseforge for MC is not on Linux. And many modpacks broke because of your mod
Just to let you know

### Solution

You could re-enable the "allow the distribution of this project outside the curseforge-overwolf ecosystem" option if you care about third party launchers (MultiMC, PolyMC, GDLauncher, ...), this is especially annoying on Linux as curseforge for MC is not on Linux

**Comment by Flemmli97** [comment]
turned on. for now
