### ISSUE TITLE
World enters strange state when jumping into centre End Portal after killing Ender Dragon

### ISSUE THREAD

**Issue by PantsWP** [Flemmli97/TenshiLib#9]
### Modloader

Forge

### Minecraft version

1.18.2

### Modloader version

40.1.0

### Mod version

tenshilib-1.18.2-1.6.7-forge

### Description

Jumping through the centre End Portal after killing the Ender Dragon doesn't send the player back to the overworld. Instead, the player remains in the place where they jumped in and the portal is rendered unusable. Furthermore, all entities have disappeared and cannot use any item that acts as a projectile (such as an ender pearl) or summon any mobs. 

Teleporting to the overworld using commands semi-fixes this issue, however entities no longer make sounds and casting any commands on a player or mob will return with the error "no entities found". 

Exiting out of a world and back in completely fixes the issue until the player attempts to jump into the End Portal again.

Tested on singleplayer, on a fresh install with this mod only. 

### Steps to reproduce

1. Go to the End
2. Kill the Ender Dragon
3. Jump into the centre portal
4. Skip the credits

### Logs

https://gist.github.com/PantsWP/2d7f9d236233a6d2014e412058c8666f

**Comment by Flemmli97** [comment]
fixed in 2e7622b33ac22720d085415ff9136086834ba781
